05 – SQL/00 – CRUD starts here/Seek_well/config/routes.rb
Rails.application.routes.draw do
  root 'ft_query#index'
  post 'create_db' => 'ft_query#create_db'
  post 'insert_time_stamp' => 'ft_query#insert_time_stamp'
  post 'update_time_stamp' => 'ft_query#update_time_stamp'
  post 'create_table' => 'ft_query#create_table'
  post 'drop_table' => 'ft_query#drop_table'
  post 'delete_last' => 'ft_query#delete_last'
  post 'destroy_all' => 'ft_query#destroy_all'
  post 'start_race' => 'ft_query#start_race'
  post 'all_by_name' => 'ft_query#all_by_name'
  post 'all_by_race' => 'ft_query#all_by_race'
end

05 – SQL/00 – CRUD starts here/Seek_well/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

05 – SQL/00 – CRUD starts here/Seek_well/app/controllers/ft_query_controller.rb
require 'sqlite3'

$db

class FtQueryController < ApplicationController
  def index
   
  end

  def create_db
    $db = SQLite3::Database.new "ft_sql.db"
    redirect_to '/'
  end

  def create_table
    clock_watch = $db.execute <<-SQL
    CREATE TABLE IF NOT EXISTS clock_watch (
      ts_id INTEGER PRIMARY KEY AUTOINCREMENT,
      day INTEGER,
      month INTEGER,
      year INTEGER,
      hour INTEGER,
      min INTEGER,
      sec INTEGER,
      race INTEGER,
      name varchar(50),
      lap INTEGER
    );
    SQL
    race = $db.execute <<-SQL
    CREATE TABLE IF NOT EXISTS race (
      r_id INTEGER PRIMARY KEY AUTOINCREMENT,
      start varchar(50)
    );
    SQL

    redirect_to '/'
  end

  def drop_table
    query1 = "DROP TABLE IF EXISTS clock_watch"
    query2 = "DROP TABLE IF EXISTS race"
    $db.execute(query1)
    $db.execute(query2)
    redirect_to '/'
  end

  def start_race
   
  end

  def insert_time_stamp
  
  end

  def delete_last

  end

  def destroy_all
   
  end

  def all_by_name
 
  end

  def all_by_race
   
  end

  def update_time_stamp
  
  end

  private


end

05 – SQL/00 – CRUD starts here/Seek_well/app/helpers/application_helper.rb
module ApplicationHelper
end

05 – SQL/00 – CRUD starts here/Seek_well/app/helpers/ft_query_helper.rb
module FtQueryHelper
end

05 – SQL/00 – CRUD starts here/Seek_well/app/views/ft_query/_all.html.erb
<!-- DO NO CHANGE THE ORDER OF DISPLAY TO MATCH YOUR RESULTS  -->
<!-- ALL THE TESTS ARE ACCORDING THIS ARRAY 'S DESIGN -->
<table>
  <thead>
    <tr>
      <td>Runner name</td>
      <td>Lap hour</td>
      <td>Lap min</td>
      <td>Lap sec</td>
      <td>Race start_time</td>
      <td>Race ID</td>
    </tr>
  </thead>
  <tbody>

        <!-- this is for message printing instead of empty records  -->
        <%$all = "" if $all.nil?%>
        <%if $all.count == 1 && $all[0].is_a?(String) %>
        <tr>
          <td colspan="6">
            <%=$all[0]%>
          </td>
        </tr>
        <%else%>
        <!-- this is for regular table display  -->
          <%$all.each do |t_s |%>
          <tr>
            <td><%=t_s[0]%></td>
            <td><%=t_s[1]%></td>
            <td><%=t_s[2]%></td>
            <td><%=t_s[3]%></td>
            <td><%=t_s[4]%></td>
            <td><%=t_s[5]%></td>
          </tr>
          <%end%>
      <%end%>
  </tbody>
</table>

05 – SQL/00 – CRUD starts here/Seek_well/app/views/ft_query/_timestamp.html.erb
<!-- DO NO CHANGE THE ORDER OF DISPLAY TO MATCH YOUR RESULTS  -->
<!-- ALL THE TESTS ARE ACCORDING THIS ARRAY 'S DESIGN -->
<table>
  <thead>
    <tr>
      <td>id</td>
      <td>day</td>
      <td>month</td>
      <td>year</td>
      <td>hour</td>
      <td>min</td>
      <td>sec</td>
      <td>race</td>
      <td>name</td>
      <td>lap</td>
    </tr>
  </thead>
  <tbody>
      <!-- this is for print message when $timestamp is empty of db records -->
      <%if $time_stamps.count == 1 && $time_stamps[0].is_a?(String) %>
        <tr>
          <td colspan="10">
            <%=$time_stamps[0]%>
          </td>
        </tr>
      <%else%>
      <!-- this is for regular table display  -->
      <%$time_stamps.reverse_each do |t_s |%>
        <tr>
          <td><%=t_s[0]%></td>
          <td><%=t_s[1]%></td>
          <td><%=t_s[2]%></td>
          <td><%=t_s[3]%></td>
          <td><%=t_s[4]%></td>
          <td><%=t_s[5]%></td>
          <td><%=t_s[6]%></td>
          <td><%=t_s[7]%></td>
          <td><%=t_s[8]%></td>
          <td><%=t_s[9]%></td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>

05 – SQL/00 – CRUD starts here/Seek_well/app/views/ft_query/index.html.erb
<section class="split" >

<div  class="row">
  <div class="query_btns" >
    <%=button_to "db_creation",create_db_path,class: "db_query" %>
    <%=button_to "table_creation",create_table_path,class: "db_query" %>
    <%=button_to "drop_table",drop_table_path ,class: "db_query" %>
    <br/>
    <%= form_tag(start_race_path , method: "post")  do  %>
    <%= submit_tag "Subscribe / Start race" ,class: "db_query"%>
    <%= text_field_tag :name_1 , $runner_1%>
    <%= text_field_tag :name_2, $runner_2%>
    <%= text_field_tag :name_3 , $runner_3%>
    <%= text_field_tag :name_4 , $runner_4%>
    <%end%>
    <br/>
    <%= form_tag(insert_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "time" ,class: "db_query"%>
    <%= text_field_tag :name_1 , $runner_1 %>
    <%end%>
    <%= form_tag(insert_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "time" ,class: "db_query"%>
    <%= text_field_tag :name_2 , $runner_2 %>
    <%end%>
    <%= form_tag(insert_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "time" ,class: "db_query"%>
    <%= text_field_tag :name_3 , $runner_3 %>
    <%end%>
    <%= form_tag(insert_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "time", class: "db_query"%>
    <%= text_field_tag :name_4 , $runner_4 %>
    <%end%>
    <br/>
    <%= form_tag(update_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "update name" ,class: "db_query"%>
    <%= text_field_tag :name_1 , $runner_1 %>
    <%end%>
    <%= form_tag(update_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "update name" ,class: "db_query"%>
    <%= text_field_tag :name_2 , $runner_2 %>
    <%end%>
    <%= form_tag(update_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "update name" ,class: "db_query"%>
    <%= text_field_tag :name_3 , $runner_3 %>
    <%end%>
    <%= form_tag(update_time_stamp_path , method: "post")  do  %>
    <%= submit_tag "update name", class: "db_query"%>
    <%= text_field_tag :name_4 , $runner_4 %>
    <%end%>
    <br/>
    <%=button_to "Show all by name",all_by_name_path,class: "db_query" %>
    <%=button_to "Show all by race",all_by_race_path,class: "db_query" %>
    <%=button_to "delete_last",delete_last_path,class: "db_query" %>
    <%=button_to "delete_all",destroy_all_path,class: "db_query" %>
  </div>
</div>
</section>
</br>

<%if false%> <!-- uncomment at ex02 -->
<div class="split"style="width:100%">
  <div class="row" style="width:100%">
    <p class="cell">
<!-- to avoid poluting page his part is in a patial named _timestamp.html.erb -->
    <%= render "timestamp"%>
    </p>
    <p class="cell">
<!-- to avoid poluting page his part is in a patial named _all.html.erb -->
    <%= render "all"%>
    </p>
  </div>
</div>
<%end%> <!-- uncomment at ex02 -->

05 – SQL/00 – CRUD starts here/Seek_well/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeekWell</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
      <div class="container">
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </body>
</html>